# Generated by Django 3.2.4 on 2021-06-29 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lwcapp', '0003_auto_20210629_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='hashtag',
        ),
        migrations.AddField(
            model_name='hashtags',
            name='key',
            field=models.ManyToManyField(to='lwcapp.Blog'),
        ),
    ]
