# Generated by Django 3.2.4 on 2021-06-29 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lwcapp', '0004_auto_20210629_1742'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hashtags',
            old_name='key',
            new_name='hashtag',
        ),
    ]
