# Generated by Django 3.2.4 on 2021-06-30 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lwcapp', '0006_auto_20210629_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='is_global',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
